### ISSUE TITLE
Win counted twice

### ISSUE THREAD

**Issue by PhracturedBlue** [oddstream/lsol#1]
I was playing classic (Klondike) solitaire on Android (sorry, I don't see a version number...it is whatever is on the Play Store right now (dated April 30, 2022).  And quite after winning a game.  I started Solitaire back up and pressed the checkbox (being new to the game, I had no idea what that would do) and it registered a 'new win in 0 moves'.

Thanks for making this game, it is excellent

**Comment by oddstream** [comment]
Hi - thanks for taking the time to report this.

I *think* you are using the old version of the Android app; the github
repro is for the newer version, called LÖVE Solitaire, which is also on the
Play Store.

The old version is kind of deprecated now, because LÖVE Solitaire is
replacing it. (The new one is very much better in many ways, and can also
be run natively on Windows/Mac/Linux.)

**Comment by PhracturedBlue** [comment]
Thank you for that.  Yes, I was using the old version and didn't realize it wasn't tied to this repository.  I have switched to LÖVE Solitaire and so-far so-good
