### ISSUE TITLE
Per game timer

### ISSUE THREAD

**Issue by geeohgeegeeoh** [oddstream/lsol#12]
Would it be possible to track time to complete an individual game, as well as the accumulated time in statistics?

**Comment by oddstream** [comment]
I've thought about this on and off for years ... at the moment there's no timer because I find one increases stress, and I play solitaire to reduce that! However, one could be added, so long as the default is to have it turned off. As you imply, would also mean adding a bunch of statistics, and detecting when the app is not in the foreground so the timer can be paused.

**Comment by oddstream** [comment]
OK, I added a discreet timer, that's always running. It doesn't start until you make your first move in the game, and (hopefully) pauses when the app isn't active. Statistics are a bit basic, because it was retro-fitted and there will be a lot of untimed games. Will appear in version 29.
